# fly.toml app configuration file generated for s3-image-explorer on 2024-11-03T20:32:50+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 's3-image-explorer'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
